app/models.py
from sqlalchemy.orm import backref
from app import db
from flask_login import UserMixin
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash
from app import login

followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)

caught_pokemon = db.Table(
    'caught_pokemon',
    db.Column('pokemon_id', db.Integer, db.ForeignKey('user.id'))
)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    email = db.Column(db.String(200), unique=True, index=True)
    password = db.Column(db.String(200))
    created_on = db.Column(db.DateTime, default=dt.utcnow)
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    followed = db.relationship('User',
                    secondary=followers,
                    primaryjoin=(followers.c.follower_id == id),
                    secondaryjoin=(followers.c.followed_id == id),
                    backref=db.backref('followers', lazy='dynamic'),
                    lazy='dynamic'
                    )
    pokemons = db.relationship('CatchPokemon', backref='trainer', lazy='dynamic')
    caught = db.relationship('User',
                    secondary = caught_pokemon,
                    primaryjoin = (caught_pokemon.c.pokemon_id == id),
                    backref = db.backref('caught_pokemon', lazy='dynamic'),
                    lazy = 'dynamic'
                    )

    # check if pokemon has already been caught
    def is_caught(self, pokemon):
        return self.caught.filter(caught_pokemon.c.pokemon_id == pokemon.id).count > 0

    # catch a pokemon
    def catch(self, pokemon):
        if not self.is_caught(pokemon):
            self.caught.append(pokemon)
            db.session.commit()
    ####
    #### 
    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)
            db.session.commit()
        
    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)
            db.session.commit()
        
    def all_follower_posts(self):
        followed = Post.query.join(followers, Post.user_id == followers.c.followed_id).filter(followers.c.follower_id == self.id)
        self_posts = Post.query.filter_by(user_id = self.id)

        all_posts = followed.union(self_posts).order_by(Post.date_posted.desc())

        return all_posts

    def __repr__(self):
        return f'<User: {self.id} | {self.email}>'

    def from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email = data['email']
        self.password = self.hash_password(data['password'])

    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    def save(self):
        db.session.add(self)
        db.session.commit()

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    date_posted = db.Column(db.DateTime, default=dt.utcnow)
    date_updated = db.Column(db.DateTime, onupdate=dt.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<id: {self.id} | Post: {self.body[:15]}>'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def edit(self, new_body):
        self.body = new_body
        self.save()

class CatchPokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    pokemon_name = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def addPokemon(self):
        pass

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField

class EnterPokemonForm(FlaskForm):
    pokemon_name = StringField('Enter Pokemon')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_moment import Moment

login = LoginManager()
login.login_view = 'auth.login'

db = SQLAlchemy()

migrate = Migrate()

moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # register plugings
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)

    # register blueprints
    from .blueprints.main import bp as main_bp
    from .blueprints.auth import bp as auth_bp
    from .blueprints.social import bp as social_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(social_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='')

from .import routes

# python -m venv venv
# Windows: venv\scripts\activate
# If the requirements.txt has pkg-resources == 0.0.0 inside of it delete this line and press save (this is something that only works with linux)
# pip install -r requirements.txt
# windows: set FLASK_APP=app.py
# windows: set FLASK_ENV=development
# flask run

# pip install python-dotenv

# pip install flask login
# pip install flask-sqlalchemy flask-migrate psycopg2
# flask db init # initialize a database
# flask db migrate # its like commiting changes into github
# flask db upgrade # like git push

app/blueprints/main/routes.py
from flask import render_template, request
import requests
from .forms import EnterPokemonForm
from flask_login import login_required, current_user
from .import bp as main
from app.models import CatchPokemon

@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    form = EnterPokemonForm()
    if request.method == 'POST':
        pokemon_name = request.form.get('pokemon_name')
        url = f'https://pokeapi.co/api/v2/pokemon/{pokemon_name}'
        response = requests.get(url)
        if response.ok:
            stats = {
                "name": response.json()["forms"][0]["name"],
                "hp": response.json()["stats"][0]["base_stat"],
                "defense": response.json()["stats"][2]["base_stat"],
                "attack": response.json()["stats"][1]["base_stat"],
                "shiny": response.json()["sprites"]["front_shiny"]
                }
            new_pokemon = CatchPokemon(user_id=current_user.id, pokemon_name=pokemon_name)
            new_pokemon.save()

            return render_template('search.html.j2', stats=stats, form=form)
    return render_template('search.html.j2', form=form)

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='')

from .import routes

app/blueprints/social/routes.py
from .import bp as social
from app.models import User, Post
from flask_login import login_required, current_user
from flask import render_template, flash, redirect, url_for, request

@social.route('/', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        body = request.form.get('body')
        new_post = Post(user_id=current_user.id, body=body)
        new_post.save()
    posts = current_user.all_follower_posts()
    return render_template('index.html.j2', posts=posts)

@social.route('/show_users')
@login_required
def show_users():
    users = User.query.all
    return render_template('show_users.html.j2', users=users)

@social.route('/follow/<int:id>')
@login_required
def follow(id):
    user_to_follow = User.query.get(id)
    current_user.follow(user_to_follow)
    flash(f'You are now following {user_to_follow.first_name} {user_to_follow.last_name}', 'success')
    return redirect(url_for('social.show_users'))

@social.route('/unfollow/<int:id>')
@login_required
def unfollow(id):
    user_to_unfollow = User.query.get(id)
    current_user.unfollow(user_to_unfollow)
    flash(f'You unfollowed {user_to_unfollow.first_name} {user_to_unfollow.last_name}', 'warning')
    return redirect(url_for('social.show_users'))

app/templates/base.html.j2
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images.favicon.16x16.png')}}">
    <link rel="manifest" href="{{url_for('static', filename='images/site.webmanifest')}}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

    {% block css %}
    {% endblock %}
    
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>

  <body>
    {% include "./includes/nav.html.j2" %}

    {% with messages = get_flashed_messages(with_categories = true) %}
      {% if messages %}
        {% for class, message in messages %}
          <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    {# {{ moment.include.moment() }} #}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/includes/_post.html.j2
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <p class="navbar-brand" href="#">POKEMON</p>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{url_for('social.index')}}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('main.search')}}">Search</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('auth.edit_profile')}}">Edit Profile</a>
              </li>
            {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('auth.registration')}}">Register</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
              </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

app/templates/index.html.j2
{% extends 'base.html.j2' %}
{% block css %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}
{% block title %}
PokeWorld
{% endblock %}

{% block content %}
<form method='POST' action='{{url_for("social.index")}}'>
    <div class='mb-3'>
        <textarea class="form-control" placeholder="Post something" name="body" style="height:100px;"></textarea>
        <button type="submit" class="btn btn-primary">Post</button>
    </div>
</form>

<h1>News Feed</h1>
{% for post in posts %}
    {% include './includes/_post.html.j2' %}
{% endfor %}
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}
{% block title%}
Login
{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{{url_for('auth.login')}}" method="POST">
  {{ form.hidden_tag() }}

  <div>
  {{ form.email.label(class="form-label") }}
  {{ form.email(class="form-control") }}
  </div>

  <div>
  {{ form.password.label(class="form-label") }}
  {{ form.password(class="form-control") }}
  </div>

  <br/>
  
  <div>
  {{ form.submit(class="btn btn-primary form-control") }}
  </div>
</form>
{% endblock %}

app/templates/registration.html.j2
{% extends 'base.html.j2' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<h1>
{% if current_user.is_authenticated %}
Edit
{% else %}
Register
{% endif %}
</h1>

<small style="color:red;">{{error}}</small>
<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.registration')}}" method="POST">
{{ form.hidden_tag() }}

{{form.first_name.label(class="form-label")}}
{{form.first_name(class="form-control", value=current_user.first_name)}}

{{form.last_name.label(class="form-label")}}
{{form.last_name(class="form-control", value=current_user.last_name)}}

{{form.email.label(class="form-label")}}
{{form.email(class="form-control", value=current_user.email)}}

{% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small><br/>
{% endfor %}

{{form.password.label(class="form-label")}}
{{form.password(class="form-control")}}

{{form.confirm_password.label(class="form-label")}}
{{form.confirm_password(class="form-control")}}

{% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small><br/>
{% endfor %}
<br/>
{{form.submit(class="btn btn-primary")}}


</form>
{% endblock %}

app/templates/search.html.j2
{% extends 'base.html.j2' %}

{% block title %}
{% endblock %}
{% block content %}
    <div class="container">
        <h3>Use the searchbar below to find the stats of your favorite Pokemon!</h3>
        <form method="POST" action="{{url_for('main.search')}}">
            <div>
            {{ form.pokemon_name.label(class="form-label") }}
            {{ form.pokemon_name(class="form-control") }}
            </div>
            <br/>
            <div>
            {{ form.submit(class="btn btn-primary form-control") }}
            </div>
        </form>
        <br/>
        {% if stats %}
        <table class="table">
        <thead>
            <tr>
              <th scope="col">Pokemon</th>
              <th scope="col">Base HP</th>
              <th scope="col">Base Defence</th>
              <th scope="col">Base Attack</th>
              <th scope="col">Front Shiny</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">{{stats["name"]}}</th>
            <td>{{stats["hp"]}}</td>
            <td>{{stats["defense"]}}</td>
            <td>{{stats["attack"]}}</td>
            <td><img src="{{stats['shiny']}}" height=100 width=100></td>
          </tr>
        </tbody>
        </table>
        {% endif %}
    </div>
{% endblock %}

app/templates/show_users.html.j2
{% extends "base.html.j2" %}

{% block content %}
    {% for user in users %}
        {% if not user.id == current.user.id %}
            <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                <img src="" class="img-fluid rounded-start" alt="user_avatar">
                </div>
                <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                    <p class="card-text">"Catchphrase"</p>
                    {% if current_user.is_following(user) %}
                        <a href="/unfollow/{{user.id}}" class="btn btn-danger">Unfollow</a>
                    {% else %}
                        <a href="/unfollow/{{user.id}}" class="btn btn-info">Follow</a>
                    {% endif %}
                </div>
                </div>
            </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}